language: node_js

node_js:
  - stable

cache:
  yarn: true
  directories:
    - node_modules

script:
  - npm run lint
  - npm run test-ci

# Send coverage data to Coveralls
after_script: "cat coverage/lcov.info | node_modules/coveralls/bin/coveralls.js"